✅ Add AWS user setup guide
oslokommune/devportal-harvest-poc pull request #13
Opened 2020-08-26 11:46 UTC by deifyed

First draft

2020-08-26 12:41 UTC, lily-es commented on docs/setup_aws_guide.md
> +5. Trykk "Attach existing policies directly".
We have to remember here to set the oslo kommune boundary policy

2020-08-26 14:24 UTC, yngvark requested changes

2020-08-26 14:24 UTC, yngvark commented on docs/setup_aws_guide.md
> +følg [disse]() stegene
TODO? I så fall kan det godt stå "TODO" i selve readme-en, så alle skjønner at det er en todo.

2020-08-26 14:24 UTC, yngvark commented on docs/setup_aws_guide.md
> +4. Velg "Next: Permissions" og følg stegene i [Konfigurer rettigheter](#-konfigurer-rettigheter)
Denne hurtiglenken funker ikke, teksten er ikke blå/klikkbar i github.

2020-08-26 14:24 UTC, yngvark commented on docs/setup_aws_guide.md
> +3. Trykk "Add permissions" og følg stegene i [Konfigurer rettigheter](#-konfigurer-rettigheter)
Denne hurtiglenken funker ikke, teksten er ikke blå/klikkbar i github.

2020-08-26 14:24 UTC, yngvark commented on docs/setup_aws_guide.md
> +2. Finn og velg policien vi lagde i "Lag en policy".
Legg til en hurtiglenke?

2020-08-26 14:24 UTC, yngvark commented on docs/setup_aws_guide.md
> +6. Trykk "Download .csv". Denne filen krypteres og sendes til
Hva med en hurtiglenke fra "krypteres" til FAQ-en under?

2020-08-26 14:24 UTC, yngvark commented on docs/setup_aws_guide.md
> +### Kryptering av fil
FAQ er jo frequently asked questions, mens dette er ikke et spørsmål. Hva med feks "Hvordan krypterer jeg?"
Det føles litt mer UX-y/brukervennlig.

2020-08-27 06:14 UTC, deifyed commented on docs/setup_aws_guide.md
> +5. Trykk "Attach existing policies directly".
@lily-es the permission boundary was only required when using roles right?

2020-08-27 07:39 UTC, lily-es commented on docs/setup_aws_guide.md
> +5. Trykk "Attach existing policies directly".
They should also be set for users too. It can be added in after a user has been created aswell.

2020-08-27 07:51 UTC, deifyed commented on docs/setup_aws_guide.md
> +5. Trykk "Attach existing policies directly".
I saw the details of how each user was ordered and Fredrik didnt mention it, so it seems this is something sopra steria does for us

2020-08-27 08:31 UTC, yngvark approved these changes
Husk å oppdatere fra byr til ooo epost etter kl 17 i dag da :trollface: 

Se 1 ny kommentar.

2020-08-27 08:31 UTC, yngvark commented on docs/setup_aws_guide.md
> +les [her](#jeg-får-ikke-lov-til-å-opprette-en-bruker) stegene
![image](https://user-images.githubusercontent.com/562343/91416775-24c2df00-e850-11ea-830d-32e88d4080e9.png)

Fjerne "stegene"?

2020-08-27 09:03 UTC, deifyed commented on docs/setup_aws_guide.md
> +les [her](#jeg-får-ikke-lov-til-å-opprette-en-bruker) stegene
auch. bra catch

2020-08-28 06:38 UTC, merged